//==============================================================================
// Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
// SPDX-License-Identifier: MIT
//
//==============================================================================

#ifndef __RN_REGISTERS_H__
#define __RN_REGISTERS_H__

// 1TB AXI Bar size: 0x000000ffffffffff
#define AXI_BAR_SIZE 0x000000ffffffffff
#define ADDR_MASK 0xffffffff

/* RecoNIC register space declaration */

/* Packet Classification register space 0x100000 - 0x102FFF
 *   -- register space for sdnet table control (not used): 0x100000 - 0x101FFF
 *   -- register space for statistics and configuration: 0x102000 - 0x102FFF
 */
#define RN_PC_BASE_ADDRESS 0x500000
#define RN_SCR_OFFSET      0x2000
#define RN_CLR_OFFSET      0x3000

// PCIe bar2 map size: 8MB
#define RN_SCR_MAP_SIZE  0x00800000

#define TIMEOUT_THRESHOLD 5000

/* Statistics and configuration register (SCR) space - 0x2000 - 0x2FFF */
// Read-only register
#define RN_SCR_VERSION                RN_PC_BASE_ADDRESS + RN_SCR_OFFSET + 0x0
#define RN_SCR_FATAL_ERR              RN_PC_BASE_ADDRESS + RN_SCR_OFFSET + 0x4
#define RN_SCR_TRMHR_REG              RN_PC_BASE_ADDRESS + RN_SCR_OFFSET + 0x8
#define RN_SCR_TRMLR_REG              RN_PC_BASE_ADDRESS + RN_SCR_OFFSET + 0xC
#define RN_SCR_TRRMHR_REG             RN_PC_BASE_ADDRESS + RN_SCR_OFFSET + 0x10
#define RN_SCR_TRRMLR_REG             RN_PC_BASE_ADDRESS + RN_SCR_OFFSET + 0x14
#define RN_SCR_TEMPLATE_REG           RN_PC_BASE_ADDRESS + RN_SCR_OFFSET + 0x200

/* Compute Logic register (clr) space - 0x3000 - 0x3FFF */
#define RN_CLR_CTL_CMD                RN_PC_BASE_ADDRESS + RN_CLR_OFFSET + 0x0
#define RN_CLR_KER_STS                RN_PC_BASE_ADDRESS + RN_CLR_OFFSET + 0x4
#define RN_CLR_JOB_SUBMITTED          RN_PC_BASE_ADDRESS + RN_CLR_OFFSET + 0x8
#define RN_CLR_JOB_COMPLETED_NOT_READ RN_PC_BASE_ADDRESS + RN_CLR_OFFSET + 0xC
// For testing purpose
#define RN_CLR_TEMPLATE               RN_PC_BASE_ADDRESS + RN_CLR_OFFSET + 0x200

/* ERNIC register space - 0x200000 - 0x3FFFFF */
// ERNIC global control status registers (GCSR)
/* NOTE:
 *   RN_RDMA_GCSR_XRNIC_PAUSE_CONF is not configured in the current design
 *   RN_RDMA_GCSR_CON_IO_CONF      is not configured in the current design
 *   RN_RDMA_GCSR_OPKTERRQBA       is not configured in the current design
 *   RN_RDMA_GCSR_OPKTERRQBAMSB    is not configured in the current design
 *   RN_RDMA_GCSR_OUTERRSTSQSZ     is not configured in the current design
 *   RN_RDMA_GCSR_OPTERRSTSQQPTRDB is not configured in the current design
 */
#define RN_RDMA_BASE_ADDRESS         0x00200000
#define RN_RDMA_GCSR_XRNICCONF        RN_RDMA_BASE_ADDRESS + 0x0100000
#define RN_RDMA_GCSR_XRNICADCONF      RN_RDMA_BASE_ADDRESS + 0x0100004
#define RN_RDMA_GCSR_XRNIC_PAUSE_CONF RN_RDMA_BASE_ADDRESS + 0x010000C
#define RN_RDMA_GCSR_MACXADDLSB       RN_RDMA_BASE_ADDRESS + 0x0100010
#define RN_RDMA_GCSR_MACXADDMSB       RN_RDMA_BASE_ADDRESS + 0x0100014
#define RN_RDMA_GCSR_IPV6XADD1        RN_RDMA_BASE_ADDRESS + 0x0100020
#define RN_RDMA_GCSR_IPV6XADD2        RN_RDMA_BASE_ADDRESS + 0x0100024
#define RN_RDMA_GCSR_IPV6XADD3        RN_RDMA_BASE_ADDRESS + 0x0100028
#define RN_RDMA_GCSR_IPV6XADD4        RN_RDMA_BASE_ADDRESS + 0x010002C
#define RN_RDMA_GCSR_IPV4XADD         RN_RDMA_BASE_ADDRESS + 0x0100070
#define RN_RDMA_GCSR_ERRBUFBA         RN_RDMA_BASE_ADDRESS + 0x0100060
#define RN_RDMA_GCSR_ERRBUFBAMSB      RN_RDMA_BASE_ADDRESS + 0x0100064
#define RN_RDMA_GCSR_ERRBUFSZ         RN_RDMA_BASE_ADDRESS + 0x0100068
#define RN_RDMA_GCSR_XRNIC_CONF_QP_EN RN_RDMA_BASE_ADDRESS + 0x0100044
#define RN_RDMA_GCSR_ERRBUFWPTR       RN_RDMA_BASE_ADDRESS + 0x010006C
#define RN_RDMA_GCSR_OPKTERRQBA       RN_RDMA_BASE_ADDRESS + 0x0100078
#define RN_RDMA_GCSR_OPKTERRQBAMSB    RN_RDMA_BASE_ADDRESS + 0x010007C
#define RN_RDMA_GCSR_OUTERRSTSQSZ     RN_RDMA_BASE_ADDRESS + 0x0100080
#define RN_RDMA_GCSR_OPTERRSTSQQPTRDB RN_RDMA_BASE_ADDRESS + 0x0100084
#define RN_RDMA_GCSR_IPKTERRQBA       RN_RDMA_BASE_ADDRESS + 0x0100088
#define RN_RDMA_GCSR_IPKTERRQBAMSB    RN_RDMA_BASE_ADDRESS + 0x010008C
#define RN_RDMA_GCSR_IPKTERRQSZ       RN_RDMA_BASE_ADDRESS + 0x0100090
#define RN_RDMA_GCSR_IPKTERRQWPTR     RN_RDMA_BASE_ADDRESS + 0x0100094
#define RN_RDMA_GCSR_DATBUFBA         RN_RDMA_BASE_ADDRESS + 0x01000A0
#define RN_RDMA_GCSR_DATBUFBAMSB      RN_RDMA_BASE_ADDRESS + 0x01000A4
#define RN_RDMA_GCSR_DATBUFSZ         RN_RDMA_BASE_ADDRESS + 0x01000A8
#define RN_RDMA_GCSR_CON_IO_CONF      RN_RDMA_BASE_ADDRESS + 0x01000AC
#define RN_RDMA_GCSR_RESPERRPKTBA     RN_RDMA_BASE_ADDRESS + 0x01000B0
#define RN_RDMA_GCSR_RESPERRPKTBAMSB  RN_RDMA_BASE_ADDRESS + 0x01000B4
#define RN_RDMA_GCSR_RESPERRSZ        RN_RDMA_BASE_ADDRESS + 0x01000B8
#define RN_RDMA_GCSR_RESPERRWRPTR     RN_RDMA_BASE_ADDRESS + 0x01000BC
#define RN_RDMA_GCSR_INSRRPKTCNT      RN_RDMA_BASE_ADDRESS + 0x0100100
#define RN_RDMA_GCSR_INAMPKTCNT       RN_RDMA_BASE_ADDRESS + 0x0100104
#define RN_RDMA_GCSR_OUTIOPKTCNT      RN_RDMA_BASE_ADDRESS + 0x0100108
#define RN_RDMA_GCSR_OUTAMPKTCNT      RN_RDMA_BASE_ADDRESS + 0x010010C
#define RN_RDMA_GCSR_LSTINPKT         RN_RDMA_BASE_ADDRESS + 0x0100110
#define RN_RDMA_GCSR_LSTOUTPKT        RN_RDMA_BASE_ADDRESS + 0x0100114
#define RN_RDMA_GCSR_ININVDUPCNT      RN_RDMA_BASE_ADDRESS + 0x0100118
//#define RN_RDMA_GCSR_INNCKPKTSTS      RN_RDMA_BASE_ADDRESS + 0x010011C
//#define RN_RDMA_GCSR_OUTRNRPKTSTS     RN_RDMA_BASE_ADDRESS + 0x0100120
#define RN_RDMA_GCSR_WQEPROCSTS       RN_RDMA_BASE_ADDRESS + 0x0100124
#define RN_RDMA_GCSR_QPMSTS           RN_RDMA_BASE_ADDRESS + 0x010012C
#define RN_RDMA_GCSR_INALLDRPPKTCNT   RN_RDMA_BASE_ADDRESS + 0x0100130
#define RN_RDMA_GCSR_INNAKPKTCNT      RN_RDMA_BASE_ADDRESS + 0x0100134
#define RN_RDMA_GCSR_OUTNAKPKTCNT     RN_RDMA_BASE_ADDRESS + 0x0100138
#define RN_RDMA_GCSR_RESPHNDSTS       RN_RDMA_BASE_ADDRESS + 0x010013C
#define RN_RDMA_GCSR_RETRYCNTSTS      RN_RDMA_BASE_ADDRESS + 0x0100140
#define RN_RDMA_GCSR_INCNPPKTCNT      RN_RDMA_BASE_ADDRESS + 0x0100174
#define RN_RDMA_GCSR_OUTCNPPKTCNT     RN_RDMA_BASE_ADDRESS + 0x0100178
#define RN_RDMA_GCSR_OUTRDRSPPKTCNT   RN_RDMA_BASE_ADDRESS + 0x010017C
#define RN_RDMA_GCSR_INTEN            RN_RDMA_BASE_ADDRESS + 0x0100180
#define RN_RDMA_GCSR_INTSTS           RN_RDMA_BASE_ADDRESS + 0x0100184
#define RN_RDMA_GCSR_RQINTSTS1        RN_RDMA_BASE_ADDRESS + 0x0100190
#define RN_RDMA_GCSR_RQINTSTS2        RN_RDMA_BASE_ADDRESS + 0x0100194
#define RN_RDMA_GCSR_RQINTSTS3        RN_RDMA_BASE_ADDRESS + 0x0100198
#define RN_RDMA_GCSR_RQINTSTS4        RN_RDMA_BASE_ADDRESS + 0x010019c
#define RN_RDMA_GCSR_RQINTSTS5        RN_RDMA_BASE_ADDRESS + 0x01001a0
#define RN_RDMA_GCSR_RQINTSTS6        RN_RDMA_BASE_ADDRESS + 0x01001a4
#define RN_RDMA_GCSR_RQINTSTS7        RN_RDMA_BASE_ADDRESS + 0x01001a8
#define RN_RDMA_GCSR_RQINTSTS8        RN_RDMA_BASE_ADDRESS + 0x01001ac
#define RN_RDMA_GCSR_CQINTSTS1        RN_RDMA_BASE_ADDRESS + 0x0100290
#define RN_RDMA_GCSR_CQINTSTS2        RN_RDMA_BASE_ADDRESS + 0x0100294
#define RN_RDMA_GCSR_CQINTSTS3        RN_RDMA_BASE_ADDRESS + 0x0100298
#define RN_RDMA_GCSR_CQINTSTS4        RN_RDMA_BASE_ADDRESS + 0x010029c
#define RN_RDMA_GCSR_CQINTSTS5        RN_RDMA_BASE_ADDRESS + 0x01002a0
#define RN_RDMA_GCSR_CQINTSTS6        RN_RDMA_BASE_ADDRESS + 0x01002a4
#define RN_RDMA_GCSR_CQINTSTS7        RN_RDMA_BASE_ADDRESS + 0x01002a8
#define RN_RDMA_GCSR_CQINTSTS8        RN_RDMA_BASE_ADDRESS + 0x01002ac

// ERNIC protection domain table registers (PDT)
#define RN_RDMA_PDT_PDPDNUM           RN_RDMA_BASE_ADDRESS + 0x00000000
#define RN_RDMA_PDT_VIRTADDRLSB       RN_RDMA_BASE_ADDRESS + 0x00000004
#define RN_RDMA_PDT_VIRTADDRMSB       RN_RDMA_BASE_ADDRESS + 0x00000008
#define RN_RDMA_PDT_BUFBASEADDRLSB    RN_RDMA_BASE_ADDRESS + 0x0000000C
#define RN_RDMA_PDT_BUFBASEADDRMSB    RN_RDMA_BASE_ADDRESS + 0x00000010
#define RN_RDMA_PDT_BUFRKEY           RN_RDMA_BASE_ADDRESS + 0x00000014
#define RN_RDMA_PDT_WRRDBUFLEN        RN_RDMA_BASE_ADDRESS + 0x00000018
#define RN_RDMA_PDT_ACCESSDESC        RN_RDMA_BASE_ADDRESS + 0x0000001C

// ERNIC per-queue control status registers (QCSR)
/* NOTE:
 *   RN_RDMA_QCSR_TIMEOUTCONFi is not configured in the current design
 */
#define RN_RDMA_QCSR_QPCONFi          RN_RDMA_BASE_ADDRESS + 0x00180000
#define RN_RDMA_QCSR_QPADVCONFi       RN_RDMA_BASE_ADDRESS + 0x00180004
#define RN_RDMA_QCSR_RQBAi            RN_RDMA_BASE_ADDRESS + 0x00180008
#define RN_RDMA_QCSR_RQBAMSBi         RN_RDMA_BASE_ADDRESS + 0x001800C0
#define RN_RDMA_QCSR_SQBAi            RN_RDMA_BASE_ADDRESS + 0x00180010
#define RN_RDMA_QCSR_SQBAMSBi         RN_RDMA_BASE_ADDRESS + 0x001800C8
#define RN_RDMA_QCSR_CQBAi            RN_RDMA_BASE_ADDRESS + 0x00180018
#define RN_RDMA_QCSR_CQBAMSBi         RN_RDMA_BASE_ADDRESS + 0x001800D0
#define RN_RDMA_QCSR_RQWPTRDBADDi     RN_RDMA_BASE_ADDRESS + 0x00180020
#define RN_RDMA_QCSR_RQWPTRDBADDMSBi  RN_RDMA_BASE_ADDRESS + 0x00180024
#define RN_RDMA_QCSR_CQDBADDi         RN_RDMA_BASE_ADDRESS + 0x00180028
#define RN_RDMA_QCSR_CQDBADDMSBi      RN_RDMA_BASE_ADDRESS + 0x0018002C
#define RN_RDMA_QCSR_CQHEADi          RN_RDMA_BASE_ADDRESS + 0x00180030
#define RN_RDMA_QCSR_RQCIi            RN_RDMA_BASE_ADDRESS + 0x00180034
#define RN_RDMA_QCSR_SQPIi            RN_RDMA_BASE_ADDRESS + 0x00180038
#define RN_RDMA_QCSR_QDEPTHi          RN_RDMA_BASE_ADDRESS + 0x0018003C
#define RN_RDMA_QCSR_SQPSNi           RN_RDMA_BASE_ADDRESS + 0x00180040
#define RN_RDMA_QCSR_LSTRQREQi        RN_RDMA_BASE_ADDRESS + 0x00180044
#define RN_RDMA_QCSR_DESTQPCONFi      RN_RDMA_BASE_ADDRESS + 0x00180048
#define RN_RDMA_QCSR_TIMEOUTCONFi     RN_RDMA_BASE_ADDRESS + 0x0018004C
#define RN_RDMA_QCSR_MACDESADDLSBi    RN_RDMA_BASE_ADDRESS + 0x00180050
#define RN_RDMA_QCSR_MACDESADDMSBi    RN_RDMA_BASE_ADDRESS + 0x00180054
#define RN_RDMA_QCSR_IPDESADDR1i      RN_RDMA_BASE_ADDRESS + 0x00180060
#define RN_RDMA_QCSR_IPDESADDR2i      RN_RDMA_BASE_ADDRESS + 0x00180064
#define RN_RDMA_QCSR_IPDESADDR3i      RN_RDMA_BASE_ADDRESS + 0x00180068
#define RN_RDMA_QCSR_IPDESADDR4i      RN_RDMA_BASE_ADDRESS + 0x0018006C
#define RN_RDMA_QCSR_STATSSNi         RN_RDMA_BASE_ADDRESS + 0x00180080
#define RN_RDMA_QCSR_STATMSNi         RN_RDMA_BASE_ADDRESS + 0x00180084
#define RN_RDMA_QCSR_STATQPi          RN_RDMA_BASE_ADDRESS + 0x00180088
#define RN_RDMA_QCSR_STATCURSQPTRi    RN_RDMA_BASE_ADDRESS + 0x0018008C
#define RN_RDMA_QCSR_STATRESPSNi      RN_RDMA_BASE_ADDRESS + 0x00180090
#define RN_RDMA_QCSR_STATRQBUFCAi     RN_RDMA_BASE_ADDRESS + 0x00180094
#define RN_RDMA_QCSR_STATWQEi         RN_RDMA_BASE_ADDRESS + 0x00180098
#define RN_RDMA_QCSR_STATRQPIDBi      RN_RDMA_BASE_ADDRESS + 0x0018009C
#define RN_RDMA_QCSR_PDi              RN_RDMA_BASE_ADDRESS + 0x001800B0
#define RN_RDMA_QCSR_STATRQBUFCAMSBi  RN_RDMA_BASE_ADDRESS + 0x001800D8

// WQE opcode: 8-bit
#define RNIC_OP_WRITE        0
#define RNIC_OP_WRITE_IMMDT  1
#define RNIC_OP_SEND         2
#define RNIC_OP_SEND_IMMDT   3
#define RNIC_OP_READ         4
#define RNIC_OP_SEND_INV     12

// QDMA AXI Bridge mapping and configuration
#define RN_QDMA_CSR_BASE_ADDRESS 0x00014000
#define AXIB_BDF_ADDR_TRANSLATE_ADDR_LSB RN_QDMA_CSR_BASE_ADDRESS + 0x00002420
#define AXIB_BDF_ADDR_TRANSLATE_ADDR_MSB RN_QDMA_CSR_BASE_ADDRESS + 0x00002424
#define AXIB_BDF_PASID_RESERVED_ADDR     RN_QDMA_CSR_BASE_ADDRESS + 0x00002428
// function number is 12-bit
#define AXIB_BDF_FUNCTION_NUM_ADDR       RN_QDMA_CSR_BASE_ADDRESS + 0x0000242C
// Map control:
// - [31:30] Read/Write Access permission, set to 2'b11
// - [29] : R0 access Error, set to 1'b0
// - [28:26] Protection ID, set to 3'd0
// - [25:0] Window Size in unit of 4K. If we use 64GB mapping, need to set it to 0x1000000
#define AXIB_BDF_MAP_CONTROL_ADDR        RN_QDMA_CSR_BASE_ADDRESS + 0x00002430
#define AXIB_BDF_RESERVED_ADDR           RN_QDMA_CSR_BASE_ADDRESS + 0x00002434
#define AXIB_BDF_MAP_CONTROL             0xC1000000

#endif  /* __RN_REGISTERS_H__ */